NotificationsApp/NotificationsApp/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NotificationsApp.Controllers
{
    [Filters.LoginFilters]
    public class ReportsController : Controller
    {
        // GET: Reports
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult OperationalReport(string orderBy = null)
        {
            List<Models.OperationalReportModel> operationalReportModel = new List<Models.OperationalReportModel>();

            var allAccounts = BLL.Services.AccountServices.LoadAllAccounts();
            var allMessages = BLL.Services.MessageServices.LoadAllMessages();
            var allPackages = BLL.Services.PackageServices.LoadAllPackages();
            allPackages = allPackages.OrderBy(p => p.MaxSubscribers).ToList();

            foreach (var account in allAccounts)
            {
                Models.OperationalReportModel tempModel = new Models.OperationalReportModel();

                tempModel.SiteName = account.Name;
                tempModel.AccountCreationDate = account.CreationDate;
                tempModel.NumberOfSubscribers = account.NumberOfSubscribers;
                tempModel.CurrentPackage = allPackages.Where(p => p.PackageID == account.PackageID).FirstOrDefault().Name;

                tempModel.NumberOfMessagesInLase30Days = allMessages.Where(m => m.AccountID == account.AccountID && m.CreationDate >= DateTime.Now.AddMonths(-1)).Count();
                tempModel.NumberOfMessagesInLase90Days = allMessages.Where(m => m.AccountID == account.AccountID && m.CreationDate >= DateTime.Now.AddMonths(-3)).Count();

                foreach (var package in allPackages)
                {
                    if (package.MaxSubscribers > account.NumberOfSubscribers)
                    {
                        tempModel.NeededPackage = package.Name;
                        break;
                    }
                }

                operationalReportModel.Add(tempModel);
            }

            if (orderBy != null && !orderBy.Equals("0"))
            {
                Auxiliary.Navigation.SortParam = orderBy;
                if (orderBy.Equals("name"))
                {
                    operationalReportModel = operationalReportModel.OrderBy(m => m.SiteName).ToList();
                    Auxiliary.Navigation.SortValue = "שם האתר";
                }
                else if (orderBy.Equals("numOfSubscribers"))
                {
                    operationalReportModel = operationalReportModel.OrderByDescending(m => m.NumberOfSubscribers).ToList();
                    Auxiliary.Navigation.SortValue = "מספר מנויים";
                }
                else if (orderBy.Equals("package"))
                {
                    operationalReportModel = operationalReportModel.OrderBy(m => m.CurrentPackage).ToList();
                    Auxiliary.Navigation.SortValue = "חבילה";
                }
                else if (orderBy.Equals("numberOfMessagesSentIn30Days"))
                {
                    operationalReportModel = operationalReportModel.OrderByDescending(m => m.NumberOfMessagesInLase30Days).ToList();
                    Auxiliary.Navigation.SortValue = "מספר הודעות שנשלחו ב30 יום האחרונים";
                }
                else if (orderBy.Equals("numberOfMessagesSentIn90Days"))
                {
                    operationalReportModel = operationalReportModel.OrderByDescending(m => m.NumberOfMessagesInLase90Days).ToList();
                    Auxiliary.Navigation.SortValue = "מספר הודעות שנשלחו ב90 יום האחרונים";
                }
            }

            return View("../Reports/OperationalReport", operationalReportModel);
        }
    }
}

NotificationsApp/NotificationsApp/Controllers/SendAutomationsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Drawing;
using Common;
using Newtonsoft.Json.Linq;

namespace NotificationsApp.Controllers
{
    public class SendAutomationsController : Controller
    {

        public ActionResult Index()
        {
            var model = ModelsServices.SendAutomationModelServices.GetSendAutomationsModelByPage(1);
            return View("~/Views/SendAutomations/_MainSendAutomations.cshtml", model);
        }
        public ActionResult GetSendAutomationsByPage(int pageNum)
        {
            var model = ModelsServices.SendAutomationModelServices.GetSendAutomationsModelByPage(pageNum);
            return View("~/Views/SendAutomations/_SendAutomationsTable.cshtml", model);
        }
        public ActionResult GetSendAutomationsByPageAndFilters_Overloading(int pageNum, int statusToProcess,string accountsDataToProcess,bool isForSingleAccount)
        {
            List<string> accountsFilters = new List<string>();
            var statusToFilter = (BLL.SendAutomationStatus)statusToProcess;
            if (!string.IsNullOrEmpty(accountsDataToProcess))
            {
                accountsFilters = accountsDataToProcess.Split(',').ToList();
            }
            
            var model = ModelsServices.SendAutomationModelServices.GetSendAutomationsModelByPageAndFilters_Overloading(pageNum,statusToFilter, accountsFilters);
            model.IsForSingleAccount = isForSingleAccount;
            return PartialView("~/Views/SendAutomations/_SendAutomationsTable.cshtml", model);
        }
        public ActionResult GetSendAutomationsByPageAndFilters(Models.SendAutomationFiltersModel filtersToProcess)
        {
            List<string> accountsFilters = new List<string>();
            BLL.SendAutomationFilters filtersModel = ModelsServices.SendAutomationFiltersModelServices.ProcessFilters(filtersToProcess);
            var model = ModelsServices.SendAutomationModelServices.GetSendAutomationsModelByPageAndFilters_Model(filtersModel);
            model.IsForSingleAccount = filtersToProcess.IsForSingleAccount;
            return PartialView("~/Views/SendAutomations/_SendAutomationsTable.cshtml", model);
        }
        //[HttpPost] //causes requests to fail in production
        public ActionResult SaveAutomation(FormCollection fc)
        {
            try
            {
                BLL.SendAutomation automationToUpdate = new BLL.SendAutomation
                {
                    TemplateMessage = new BLL.Message()
                };
                dynamic inTemplateMessage = new JObject();
                var now = DateTime.Now;
                int accountID = -1;
                int automationID = -1;

                var fileManager = FileManager.GetInstance();
                ManagedFile prevTemplateNotificationImage = null;



                if (fc["automation-id"] != null && int.TryParse(fc["automation-id"], out automationID))
                {
                    automationToUpdate.SendAutomationID = automationID;
                    automationToUpdate = Services.SendAutomationServices.LoadByID(automationID);
                    if (automationToUpdate == null)
                    {
                        return Content("לא ניתן לערוך את האוטומציה");
                    }
                }

                if (Request.Files.Count > 0 && Request.Files[0].ContentLength > 0) //overrides or new image is linked
                {
                    HttpPostedFileBase file = Request.Files[0];
                    //var img = Image.FromStream(file.InputStream, true, true);
                    var newTemplateNotificationImage = fileManager.SaveFile(file);

                    if (!string.IsNullOrEmpty(automationToUpdate.TemplateMessage.ImageUrl)) 
                    {
                        prevTemplateNotificationImage = Newtonsoft.Json.JsonConvert.DeserializeObject<Common.ManagedFile>(automationToUpdate.TemplateMessage.ImageUrl);

                    }
                    //TODO: not ideal to save as string on BLL
                    automationToUpdate.TemplateMessage.ImageUrl = Newtonsoft.Json.JsonConvert.SerializeObject(newTemplateNotificationImage);
                }

                inTemplateMessage.DisplayName = fc["message-name"];
                inTemplateMessage.Headline = fc["message-headline"];
                inTemplateMessage.MessageText = fc["message-text"];
                inTemplateMessage.ButtonText = fc["message-redirect-btn-text"];
                inTemplateMessage.ButtonRedirectLink = fc["message-redirect-link"];
                if (!BLL.Services.MessageServices.ValidateInputAndPopulateMessage(inTemplateMessage, automationToUpdate.TemplateMessage, -1))
                {
                    //end and return result accordingly
                    return Content("פרטי ההודעה שגויים");
                }
                if (!int.TryParse(fc["account-id"], out accountID))
                {
                    return Content("מזהה החשבון שגוי");
                }
                automationToUpdate.AccountID = accountID;
                automationToUpdate.TemplateMessage.AccountID = accountID;
                automationToUpdate.DisplayName = fc["automation-name"];
                if (string.IsNullOrEmpty(automationToUpdate.DisplayName))
                {
                    return Content("שם האוטומציה חסר");
                }

                automationToUpdate.Day = (DayOfWeek)int.Parse(fc["automation-day"]);
                automationToUpdate.Hour = int.Parse(fc["automation-hour"]);

                automationToUpdate.IsActive = true;
                automationToUpdate.CreationDate = now;

                automationID = Services.SendAutomationServices.Save(automationToUpdate);
                if (automationID <= 0)
                {
                    return Content("השמירה נכשלה");
                }

                if (prevTemplateNotificationImage != null) //delete previous image only if save succeeded and image was updated
                {
                    fileManager.DeleteFile(prevTemplateNotificationImage);
                }

                return Content("השמירה התבצעה בהצלחה");
            }
            catch (Exception ex)
            {
                return Content(ex.ToString());
            }
        }
        public ActionResult CreateOrUpdateAutomation(int sendAutomationID = 0)
        {
            var model = new Models.UpdateSendAutomationModel();
            if (sendAutomationID != 0)
            {
                model.SendAutomation = Services.SendAutomationServices.LoadByID(sendAutomationID);
                model.Account = BLL.Services.AccountServices.LoadAccountByID(model.SendAutomation.AccountID);
            }
            return View("~/Views/SendAutomations/_UpdateSendAutomations.cshtml", model);
        }
        public ActionResult CreateAutomationForAccount(int accountID)
        {
            var model = new Models.UpdateSendAutomationModel();
            ActionResult errorResult = Content("לא ניתן לייצר אוטומציה עבור חשבון זה כי אינו קיים במערכת");
            if (accountID == 0)
            {
                return errorResult;
            }
            model.Account = BLL.Services.AccountServices.LoadAccountByID(accountID);
            if (model.Account.AccountID == 0)
            {
                return errorResult;
            }
            return View("~/Views/SendAutomations/_UpdateSendAutomations.cshtml", model);
        }
        public ActionResult DeleteAutomation(int automationID)
        {
            bool isSuccess = Services.SendAutomationServices.Delete(automationID);
            return Content(isSuccess.ToString());
        }
        public ActionResult ToggleStatus(int automationID)
        {
            var automation = Services.SendAutomationServices.LoadByID(automationID);
            if (automation.SendAutomationID == 0)
            {
                return null;
            }
            automation.IsActive = !automation.IsActive;
            int saveStatus = Services.SendAutomationServices.Save(automation);
            if (saveStatus == -1)
            {
                return null;
            }
            return Content(automation.IsActive.ToString());
        }

    }

}

NotificationsApp/NotificationsApp/Views/Home/Home.cshtml
@model NotificationsApp.Models.AccountModel
@{
    ViewBag.Title = "AdminHome";
}

<div id="PageContainer">


    @if (Model.ErrorCode != 0)
    {
        if (Model.ErrorCode == 1)
        {
            <script>
                alert("החשבון לא נוצר בפולסים, אנא נסה שנית");
            </script>
        }
        else if (Model.ErrorCode == 2)
        {
            <script>
                alert("החשבון לא נוצר בדאטה בייס, אנא נסה שנית");
            </script>
        }
        else if (Model.ErrorCode == 3 || Model.ErrorCode == 4)
        {
            <script>
                alert("השמירה נכשלה! - " + @(Model.ErrorMsg));
            </script>
        }
    }
    <br />
    <div class="Button Navigation ">
        <button onclick="AddNewAccount()" class="btn-primary"><b>הוסף חשבון חדש</b></button>
        <button onclick="OperationalReport()" class="btn-primary"><b>דו"ח תפעולי</b></button>
        <button onclick="ManageSendAutomations()" class="btn-primary"><b>טבלת אוטומציות</b></button>
    </div>

    <br /> <br /> <br />

    <div class="Headline">
        <h2><b>טבלת חשבונות במערכת</b></h2>
    </div>

    @*<div class="Filters">
        @Html.Partial("~/Views/Accounts/_AccountsTableFilters.cshtml", Model)
        <div class="lds-hourglass" style="display:none"></div>
    </div>*@

    <div id="AccountsTable">
        <table>
            <tr style="color:white">
                <th>שם החשבון</th>
                <th>Account Key</th>
                <th>Notification Key</th>
                <th>מספר מנויים</th>
                <th>סוג חבילה</th>
                <th>מחק חשבון</th>
                <th>ערוך חשבון</th>
            </tr>
            @foreach (var account in Model.ListOfAccounts)
            {
                <tr class="TableRow">
                    <td>
                        @account.Name
                    </td>
                    <td>
                        @account.AccountKey
                    </td>
                    <td>
                        @account.Data.Credentials.PulseemNotificationKey
                    </td>
                    <td>
                        @account.NumberOfSubscribers
                    </td>
                    <td>
                        @{
                            var packageName = Model.ListOfPackages.Where(p => account.PackageID == p.PackageID).FirstOrDefault().Name;
                        }
                        @packageName
                    </td>
                    <td>
                        <input type="button" onclick="DeleteAccount(@account.AccountID)" value="מחק" />
                    </td>
                    <td>
                        <input type="button" onclick="EditAccount(@account.AccountID)" value="ערוך" />
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

<script type="text/javascript">

    function EditAccount(accountID) {
        document.location.href = '@Url.Action("EditAccount", "Home")' + "?accountID=" + accountID
    }

    function DeleteAccount(accountID) {
        var result = confirm("את/ה בטוח/ה שברצונך למחוק משתמש זה?");
            if (result) {
                $.post("@Url.Action("DeleteAccount", "Home")" + "?accountID=" + accountID, function (data) {
                    $('#PageContainer').html(data);
                });
        }
    }

    function AddNewAccount() {
        document.location.href = '@Url.Action("AddNewAccount", "Home")';
    }

    function OperationalReport() {
        document.location.href = '@Url.Action("OperationalReport", "Reports")';
    }
    function ManageSendAutomations() {
        document.location.href = '@Url.Action("Index", "SendAutomations")';
    }


</script>

<style>
    table { table-layout: auto; width: 100%; }
    .Headline { text-align: center; background: #aea8a8; padding-top: 1mm; padding-bottom: 5mm; margin-bottom: 30px; }
    .Button { font-size: 22px; padding-top: 25px; text-align: center; }
    #AccountsTable { border-bottom: ridge; width: 100%; }
    #AccountsTable table th { border-left: 2px solid #808080; border-right: 2px solid #808080; padding: 3px 9px 3px 9px; background: #4a4848; text-align: center; }
    #AccountsTable table td { border-left: 1px solid #808080; border-right: 1px solid #808080; padding: 3px 9px 3px 9px; text-align: center; }
    .TableRow:nth-child(odd) { background: #CCC }
</style>