NotificationsApp/NotificationsApp/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NotificationsApp.Controllers
{
    public class TestsController : Controller
    {
        public bool ChangeLastSendDateToSendAutomation(int sendAutomationID,int hoursToAdd)
        {
            return Services.SendAutomationServices.ChangeLastSendDateToAutomation(sendAutomationID, 7, hoursToAdd);

        }
        public ActionResult TestGet()
        {
            return Content("TEST OK");
        }
        public ActionResult GetTestPost()
        {
            return PartialView("~/Views/Tests/_TestPost.cshtml");
        }
        public ActionResult TestPost(FormCollection fc)
        {
            string result = "OK";
            if (fc == null || fc.Keys.Count == 0)
            {
                result = "fc empty";
            }
            return Content(result);
        }
        public ActionResult Scrollable()
        {
            return View("~/Views/Tests/_Scrollable.cshtml");
        }
    }
}

NotificationsApp/NotificationsApp/Views/Tests/_Scrollable.cshtml
<div style="height:100vh; background-color:green;">

</div>
<div style="height:100vh; background-color:red;">

</div>
<div style="height:100vh; background-color:blue;">

</div>
<script>
    $(document).ready(function () {
        $("body").slimScroll({
            color: "#2596be",
        });
    })
</script>

NotificationsApp/NotificationsApp/Views/Tests/_TestPost.cshtml
<form id="TestMyShitForm" name="send-automation-add-form" class="send-automations__add--form" method="post" action="@Url.Action("TestPost", "Tests")">
    <input name="input-name" value="stuff" />
    <div>
        <button type="submit">שגר ושכח</button>
    </div>
</form>
<script>
    $(document).ready(function () {
        $("#TestMyShitForm").submit(function (e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr("action"),
                type: $(this).attr("method"),
                data: new FormData(this),
                processData: false,
                contentType: false,
                success: function (data) {
                    alert(data);
                },
                error: function (xhr, status, error) {
                    var err = eval("(" + xhr.responseText + ")");
                    alert(err.Message);
                }
        });
    });
</script>